<?php
/**
 * @file
 * stanford_benefits.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function stanford_benefits_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-benefit-body'.
  $field_instances['node-benefit-body'] = array(
    'bundle' => 'benefit',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the overview for the benefit.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'stanford_field_formatters',
        'settings' => array(
          'html_tag' => '',
          'image_style' => '',
          'link_field' => '',
          'trim_length' => 600,
        ),
        'type' => 'stanford_link_formatter_link_to_field',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Overview',
    'required' => 1,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'content_editor_text_format' => 'content_editor_text_format',
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'content_editor_text_format' => array(
              'weight' => -10,
            ),
            'filtered_html' => array(
              'weight' => 0,
            ),
            'full_html' => array(
              'weight' => 1,
            ),
            'plain_text' => array(
              'weight' => 10,
            ),
          ),
        ),
      ),
      'display_summary' => 0,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 1,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-benefit-field_access_services'.
  $field_instances['node-benefit-field_access_services'] = array(
    'bundle' => 'benefit',
    'default_value' => array(
      0 => array(
        'value' => 'null',
      ),
    ),
    'deleted' => 0,
    'description' => 'Enter star rating for this criteria.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'starrating',
        'settings' => array(
          'fill_blank' => 1,
          'icon_color' => 1,
          'icon_type' => 'star',
        ),
        'type' => 'starrating_rating_formatter',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_access_services',
    'label' => 'Access & Services',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'starrating',
      'settings' => array(),
      'type' => 'starrating_rating_widget',
      'weight' => 14,
    ),
  );

  // Exported field_instance: 'node-benefit-field_employee_type'.
  $field_instances['node-benefit-field_employee_type'] = array(
    'bundle' => 'benefit',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'What kind of employee/retiree is this benefit for?',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_employee_type',
    'label' => 'Employee Type',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-benefit-field_full_time_employee_contrib'.
  $field_instances['node-benefit-field_full_time_employee_contrib'] = array(
    'bundle' => 'benefit',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Please enter the Full-Time Employee * Contribution Per Pay Period',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_full_time_employee_contrib',
    'label' => 'Full-Time Employee * Contribution Per Pay Period',
    'required' => 1,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'content_editor_text_format' => 'content_editor_text_format',
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'content_editor_text_format' => array(
              'weight' => -10,
            ),
            'filtered_html' => array(
              'weight' => 0,
            ),
            'full_html' => array(
              'weight' => 1,
            ),
            'plain_text' => array(
              'weight' => 10,
            ),
          ),
        ),
      ),
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 1,
      ),
      'type' => 'text_textarea',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-benefit-field_getting_better'.
  $field_instances['node-benefit-field_getting_better'] = array(
    'bundle' => 'benefit',
    'default_value' => array(
      0 => array(
        'value' => 'null',
      ),
    ),
    'deleted' => 0,
    'description' => 'Enter star rating for this criteria.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'starrating',
        'settings' => array(
          'fill_blank' => 1,
          'icon_color' => 1,
          'icon_type' => 'star',
        ),
        'type' => 'starrating_rating_formatter',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_getting_better',
    'label' => 'Getting Better',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'starrating',
      'settings' => array(),
      'type' => 'starrating_rating_widget',
      'weight' => 17,
    ),
  );

  // Exported field_instance: 'node-benefit-field_living_with_illness'.
  $field_instances['node-benefit-field_living_with_illness'] = array(
    'bundle' => 'benefit',
    'default_value' => array(
      0 => array(
        'value' => 'null',
      ),
    ),
    'deleted' => 0,
    'description' => 'Enter star rating for this criteria.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'starrating',
        'settings' => array(
          'fill_blank' => 1,
          'icon_color' => 1,
          'icon_type' => 'star',
        ),
        'type' => 'starrating_rating_formatter',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_living_with_illness',
    'label' => 'Living With Illness',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'starrating',
      'settings' => array(),
      'type' => 'starrating_rating_widget',
      'weight' => 18,
    ),
  );

  // Exported field_instance: 'node-benefit-field_overall_accredition_status'.
  $field_instances['node-benefit-field_overall_accredition_status'] = array(
    'bundle' => 'benefit',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'National Committee For Quality Assurance (NCQA) - Health Plan Report Card: <a href="http://reportcard.ncqa.org" target="_blank">http://reportcard.ncqa.org</a>',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_overall_accredition_status',
    'label' => 'Overall Accredition Status',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'node-benefit-field_part_time_employee_contrib'.
  $field_instances['node-benefit-field_part_time_employee_contrib'] = array(
    'bundle' => 'benefit',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Please enter the Part-Time Employee * Contribution Per Pay Period',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_part_time_employee_contrib',
    'label' => 'Part-Time Employee * Contribution Per Pay Period',
    'required' => 1,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'content_editor_text_format' => 'content_editor_text_format',
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'content_editor_text_format' => array(
              'weight' => -10,
            ),
            'filtered_html' => array(
              'weight' => 0,
            ),
            'full_html' => array(
              'weight' => 1,
            ),
            'plain_text' => array(
              'weight' => 10,
            ),
          ),
        ),
      ),
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 1,
      ),
      'type' => 'text_textarea',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-benefit-field_pre_authorization_require'.
  $field_instances['node-benefit-field_pre_authorization_require'] = array(
    'bundle' => 'benefit',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the Pre-Authorization Requirement for the benefit.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 10,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_pre_authorization_require',
    'label' => 'Pre-Authorization Requirement',
    'required' => 1,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'content_editor_text_format' => 'content_editor_text_format',
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'content_editor_text_format' => array(
              'weight' => -10,
            ),
            'filtered_html' => array(
              'weight' => 0,
            ),
            'full_html' => array(
              'weight' => 1,
            ),
            'plain_text' => array(
              'weight' => 10,
            ),
          ),
        ),
      ),
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'node-benefit-field_qualified_providers'.
  $field_instances['node-benefit-field_qualified_providers'] = array(
    'bundle' => 'benefit',
    'default_value' => array(
      0 => array(
        'value' => 'null',
      ),
    ),
    'deleted' => 0,
    'description' => 'Enter star rating for this criteria.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'starrating',
        'settings' => array(
          'fill_blank' => 1,
          'icon_color' => 1,
          'icon_type' => 'star',
        ),
        'type' => 'starrating_rating_formatter',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_qualified_providers',
    'label' => 'Qualified Providers',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'starrating',
      'settings' => array(),
      'type' => 'starrating_rating_widget',
      'weight' => 15,
    ),
  );

  // Exported field_instance: 'node-benefit-field_s_benefit_description'.
  $field_instances['node-benefit-field_s_benefit_description'] = array(
    'bundle' => 'benefit',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the description of for this benefit.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_s_benefit_description',
    'label' => 'Description',
    'required' => 1,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'content_editor_text_format' => 'content_editor_text_format',
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'content_editor_text_format' => array(
              'weight' => -10,
            ),
            'filtered_html' => array(
              'weight' => 0,
            ),
            'full_html' => array(
              'weight' => 1,
            ),
            'plain_text' => array(
              'weight' => 10,
            ),
          ),
        ),
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-benefit-field_staying_healthy'.
  $field_instances['node-benefit-field_staying_healthy'] = array(
    'bundle' => 'benefit',
    'default_value' => array(
      0 => array(
        'value' => 'null',
      ),
    ),
    'deleted' => 0,
    'description' => 'Enter star rating for this criteria.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'starrating',
        'settings' => array(
          'fill_blank' => 1,
          'icon_color' => 1,
          'icon_type' => 'star',
        ),
        'type' => 'starrating_rating_formatter',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staying_healthy',
    'label' => 'Staying Healthy',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'starrating',
      'settings' => array(),
      'type' => 'starrating_rating_widget',
      'weight' => 16,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Access & Services');
  t('Description');
  t('Employee Type');
  t('Enter star rating for this criteria.');
  t('Enter the Pre-Authorization Requirement for the benefit.');
  t('Enter the description of for this benefit.');
  t('Enter the overview for the benefit.');
  t('Full-Time Employee * Contribution Per Pay Period');
  t('Getting Better');
  t('Living With Illness');
  t('National Committee For Quality Assurance (NCQA) - Health Plan Report Card: <a href="http://reportcard.ncqa.org" target="_blank">http://reportcard.ncqa.org</a>');
  t('Overall Accredition Status');
  t('Overview');
  t('Part-Time Employee * Contribution Per Pay Period');
  t('Please enter the Full-Time Employee * Contribution Per Pay Period');
  t('Please enter the Part-Time Employee * Contribution Per Pay Period');
  t('Pre-Authorization Requirement');
  t('Qualified Providers');
  t('Staying Healthy');
  t('What kind of employee/retiree is this benefit for?');

  return $field_instances;
}
