<?php
/**
 * @file
 * Code for the stanford_benefits feature.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function stanford_benefits_preprocess_page(&$vars) {
  $arg1 = arg(1);

  if ($arg1 == "4013") {
    drupal_add_css(drupal_get_path("module", "stanford_benefits") . "/css/stanford-benefits.css");
    drupal_add_js(drupal_get_path("module", "stanford_benefits") . "/js/stanford-benefits.js");
  }
}
